# Generated by Django 3.2 on 2022-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Адрес места'),
            preserve_default=False,
        ),
    ]
