# Generated by Django 3.2 on 2022-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0002_auto_20220507_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='lng',
        ),
    ]
