# Generated by Django 3.2 on 2022-04-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220422_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('c', 'Наличными'), ('o', 'Электронно')], db_index=True, default='c', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
