# Generated by Django 3.2 on 2022-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Обработанный'), ('u', 'Необработанный')], db_index=True, default='u', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
