# Generated by Django 3.2 on 2022-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(null=True, related_name='orders', to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
    ]
