# Generated by Django 3.2 on 2022-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('c', 'Наличными'), ('o', 'Электронно')], db_index=True, max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
